name: ci
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

defaults:
  run:
    # NOTE: A bit stricter than the default bash options used by GitHub Actions
    # (bash --noprofile --norc -e -o pipefail {0})
    shell: bash --noprofile --norc -euo pipefail {0}

# NOTE: Set concurrency for the current workflow to 1
concurrency: ci-${{ github.ref }}-${{ github.workflow }}

jobs:
  build-and-release:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - uses: capralifecycle/actions-lib/check-runtime-dependencies@e3bb96046b8b72962d3f08971adde45017d09346 # v1.5.1

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20

      - uses: capralifecycle/actions-lib/configure-npm@e3bb96046b8b72962d3f08971adde45017d09346 # v1.5.1

      - name: install dependencies
        run: npm ci

      - name: lint
        run: npm run lint

      - name: prepare
        run: npm run test

      - name: conditionally semantic release
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SHARED_NPMJS_TOKEN }}
        run: npm run semantic-release
